### ISSUE TITLE
Fix StackPanel

### ISSUE THREAD

**Issue by anovstrup** [scalagwt/scalagwt-sample#1]
The Showcase StackPanel demo is not working.

**Comment by anovstrup** [comment]
This is apparently caused by a ClassManifest.newArray.

**Comment by anovstrup** [comment]
Resulting from `contactNames.zip(contactEmails)` in `createContactsItem`.

**Comment by gkossakowski** [comment]
Link to the offending line:
https://github.com/scalagwt/scalagwt-sample/blob/master/src/com/google/gwt/sample/showcase/client/content/lists/CwStackPanel.scala#L187

What if you try `contactNames.toList.zip(contactEmails)`?
