### ISSUE TITLE
Convert Showcase i18n

### ISSUE THREAD

**Issue by anovstrup** [scalagwt/scalagwt-sample#8]
Convert the Java class in the com.google.gwt.sample.showcase.client.content.i18n package to Scala.

**Comment by stephenh** [comment]
Assign to me? I've got it converted locally. Not in a pull request yet.

**Comment by anovstrup** [comment]
Assigned to stephenh.

**Comment by anovstrup** [comment]
Closed by 713835b

**Comment by anovstrup** [comment]
Oops... there are some lingering Java interfaces to convert.

**Comment by anovstrup** [comment]
Closed by https://github.com/scalagwt/scalagwt-sample/pull/12.
