### ISSUE TITLE
Convert Showcase StylesheetLoader

### ISSUE THREAD

**Issue by anovstrup** [scalagwt/scalagwt-sample#9]
Convert com.google.gwt.sample.showcase.client.StyleSheetLoader to Scala.

**Comment by stephenh** [comment]
This won't be doable for the foreseeable future because StylesheetLoader uses JSNI. Well, I suppose we could move the one JSNI method out to a helper class. Most of it is straight Java.

**Comment by anovstrup** [comment]
Closed by https://github.com/scalagwt/scalagwt-sample/pull/16.
